#!/usr/bin/env python

DEBUG = True

CLIENT_RPI_CLIENT_KEY = 'raspberry_pi_client_key'
SERVER_SOCKET_PORT = 1724
SERVER_IP = '118.190.66.157'
SERVER_IDENTITY_TOKEN = 'aaabbbccc'

# GPIO
GPIO_ALERT_OUTPUT_DATA = 35
GPIO_ALERT_OUTPUT_VCC = 32
